use super::*;

impl GameLoop {
    pub(crate) fn run_turn_state_machine(
        &mut self,
        game: &mut GameState,
        agents: &mut [Box<dyn PlayerAgent>],
    ) {
        // Run BeginTurn replacement effects before the turn begins.
        let active = game.active_player();
        {
            use crate::replacement::replacement_handler::{apply_replacements, ReplacementEvent};
            use crate::replacement::ReplacementResult;
            let mut event = ReplacementEvent::BeginTurn { player: active };
            let result = apply_replacements(game, &mut event);
            if result == ReplacementResult::Skipped || result == ReplacementResult::Replaced {
                return;
            }
        }

        // Fire TurnBegin trigger at the start of each turn.
        let active = game.active_player();
        self.trigger_handler
            .handle_player_defined_del_triggers(active);
        self.trigger_handler.run_trigger(
            TriggerType::TurnBegin,
            RunParams {
                player: Some(active),
                ..Default::default()
            },
            false,
        );

        let mut state = TurnMachineState::Untap;
        while !game.game_over && state != TurnMachineState::Done {
            // EndTurn (issue #22): if end_turn_requested, skip directly to cleanup.
            if game.end_turn_requested
                && state != TurnMachineState::Cleanup
                && state != TurnMachineState::Done
            {
                game.end_turn_requested = false;
                self.combat.clear_with_cards(&mut game.cards);
                state = TurnMachineState::Cleanup;
                continue;
            }
            state = match state {
                TurnMachineState::Untap => {
                    // SkipPhase: skip untap if flag set
                    let active = game.active_player();
                    if game.player(active).skip_next_untap {
                        game.player_clear_skip_untap(active);
                        TurnMachineState::Upkeep
                    } else {
                        self.apply_turn_event(
                            game,
                            agents,
                            TurnEvent::EnterPhase {
                                phase: PhaseType::Untap,
                                emit_phase_trigger: false,
                            },
                        );
                        self.apply_turn_event(game, agents, TurnEvent::UntapStep);
                        TurnMachineState::Upkeep
                    }
                }
                TurnMachineState::Upkeep => {
                    self.apply_turn_event(
                        game,
                        agents,
                        TurnEvent::EnterPhase {
                            phase: PhaseType::Upkeep,
                            emit_phase_trigger: true,
                        },
                    );
                    self.apply_turn_event(
                        game,
                        agents,
                        TurnEvent::PriorityWindow {
                            is_main_phase: false,
                        },
                    );
                    // Cumulative upkeep is now handled as a Phase trigger
                    // (generated by generate_keyword_triggers from the keyword),
                    // so it fires alongside other upkeep triggers (e.g. Deep Spawn)
                    // and is ordered by the player. No separate procedural call needed.
                    TurnMachineState::Draw
                }
                TurnMachineState::Draw => {
                    // SkipPhase: skip draw if flag set
                    let active = game.active_player();
                    if game.player(active).skip_next_draw {
                        game.player_clear_skip_draw(active);
                        TurnMachineState::Main1
                    } else {
                        // Java parity: Java's isSkippingPhase(DRAW) returns true on turn 1
                        // in a 2-player game, skipping the entire Draw phase (no draw, no
                        // priority window). Rust skips the draw card itself but was still
                        // giving a priority window, consuming 2 extra RNG calls on Turn 1.
                        let skip_draw_phase = game.turn.turn_number == 1 && game.players.len() == 2;
                        if skip_draw_phase {
                            TurnMachineState::Main1
                        } else {
                            self.apply_turn_event(
                                game,
                                agents,
                                TurnEvent::EnterPhase {
                                    phase: PhaseType::Draw,
                                    emit_phase_trigger: true,
                                },
                            );
                            self.apply_turn_event(game, agents, TurnEvent::DrawStep);
                            self.apply_turn_event(
                                game,
                                agents,
                                TurnEvent::PriorityWindow {
                                    is_main_phase: false,
                                },
                            );
                            TurnMachineState::Main1
                        }
                    }
                }
                TurnMachineState::Main1 => {
                    self.apply_turn_event(
                        game,
                        agents,
                        TurnEvent::EnterPhase {
                            phase: PhaseType::Main1,
                            emit_phase_trigger: true,
                        },
                    );
                    if game
                        .cards_in_zone(ZoneType::Battlefield, game.active_player())
                        .iter()
                        .any(|&card_id| {
                            game.card(card_id)
                                .type_line
                                .subtypes
                                .iter()
                                .any(|s| s.eq_ignore_ascii_case("Attraction"))
                        })
                    {
                        crate::ability::effects::roll_dice_effect::roll_to_visit_attractions(
                            game,
                            &mut self.trigger_handler,
                            &mut *self.game_rng,
                            agents,
                            &mut self.mana_pools,
                            game.active_player(),
                        );
                    }
                    self.apply_turn_event(
                        game,
                        agents,
                        TurnEvent::PriorityWindow {
                            is_main_phase: true,
                        },
                    );
                    TurnMachineState::Combat
                }
                TurnMachineState::Combat => {
                    // SkipPhase: skip combat if flag set
                    let active = game.active_player();
                    if game.player(active).skip_next_combat {
                        game.player_clear_skip_combat(active);
                        TurnMachineState::Main2
                    } else {
                        self.apply_turn_event(game, agents, TurnEvent::CombatStep);
                        // Extra combat phases (issue #22, AddPhase effect)
                        if game.extra_combat_phases > 0 {
                            game.extra_combat_phases -= 1;
                            TurnMachineState::Combat // loop back for another combat
                        } else {
                            TurnMachineState::Main2
                        }
                    }
                }
                TurnMachineState::Main2 => {
                    self.apply_turn_event(
                        game,
                        agents,
                        TurnEvent::EnterPhase {
                            phase: PhaseType::Main2,
                            emit_phase_trigger: true,
                        },
                    );
                    self.apply_turn_event(
                        game,
                        agents,
                        TurnEvent::PriorityWindow {
                            is_main_phase: true,
                        },
                    );
                    TurnMachineState::EndOfTurn
                }
                TurnMachineState::EndOfTurn => {
                    self.apply_turn_event(
                        game,
                        agents,
                        TurnEvent::EnterPhase {
                            phase: PhaseType::EndOfTurn,
                            emit_phase_trigger: true,
                        },
                    );
                    self.apply_turn_event(
                        game,
                        agents,
                        TurnEvent::PriorityWindow {
                            is_main_phase: false,
                        },
                    );
                    TurnMachineState::Cleanup
                }
                TurnMachineState::Cleanup => {
                    self.apply_turn_event(
                        game,
                        agents,
                        TurnEvent::EnterPhase {
                            phase: PhaseType::Cleanup,
                            emit_phase_trigger: false,
                        },
                    );
                    self.apply_turn_event(game, agents, TurnEvent::CleanupStep);
                    self.apply_turn_event(game, agents, TurnEvent::AdvanceTurn);
                    TurnMachineState::Done
                }
                TurnMachineState::Done => TurnMachineState::Done,
            };
        }
    }

    fn apply_turn_event(
        &mut self,
        game: &mut GameState,
        agents: &mut [Box<dyn PlayerAgent>],
        event: TurnEvent,
    ) {
        if game.game_over {
            return;
        }
        match event {
            TurnEvent::EnterPhase {
                phase,
                emit_phase_trigger,
            } => {
                // Clear undo stack on phase change (can't undo across phases).
                game.stack.clear_undo_stack();

                // Run BeginPhase replacement effects before entering the phase.
                {
                    use crate::replacement::replacement_handler::{
                        apply_replacements, ReplacementEvent,
                    };
                    use crate::replacement::ReplacementResult;
                    let active = game.active_player();
                    let mut event = ReplacementEvent::BeginPhase { player: active };
                    let result = apply_replacements(game, &mut event);
                    if result == ReplacementResult::Skipped || result == ReplacementResult::Replaced
                    {
                        return;
                    }
                }

                // LKI: Snapshot battlefield state before phase transition.
                // Mirrors Java PhaseHandler line 1103: game.copyLastState().
                game.copy_last_state();
                self.set_phase(game, agents, phase);
                if emit_phase_trigger {
                    self.emit_phase_trigger(game, agents, phase);
                }
                // Suspend: at the beginning of each upkeep, remove a time counter
                // from each suspended card in exile. If last counter removed, cast for free.
                if phase == PhaseType::Upkeep {
                    self.process_suspend_upkeep(game, agents);
                }
            }
            TurnEvent::PriorityWindow { is_main_phase } => {
                self.step_with_priority(game, agents, is_main_phase);
            }
            TurnEvent::UntapStep => {
                self.with_shared_state_mutation(game, agents, |this, game, agents| {
                    this.step_untap(game, agents);
                });
            }
            TurnEvent::DrawStep => {
                self.with_shared_state_mutation(game, agents, |this, game, _agents| {
                    this.step_draw(game);
                });
            }
            TurnEvent::CombatStep => {
                self.step_combat(game, agents);
            }
            TurnEvent::CleanupStep => {
                self.with_shared_state_mutation(game, agents, |this, game, agents| {
                    this.step_cleanup(game, agents);
                });
            }
            TurnEvent::AdvanceTurn => {
                self.with_shared_state_mutation(game, agents, |_this, game, _agents| {
                    // Rotate stack's turn-tracking (this_turn_cast → last_turn_cast).
                    game.stack.on_next_turn();
                    // Reset zone turn tracking for all zones.
                    for zone in game.zones.values_mut() {
                        zone.reset_cards_added_this_turn();
                    }
                    let player_order = game.player_order.clone();
                    if let Some((player, _skip)) =
                        game.turn.advance_turn(&mut game.extra_turns, &player_order)
                    {
                        game.player_set_skip_untap(player);
                    }
                });
            }
        }
    }

    pub fn step_untap(&mut self, game: &mut GameState, agents: &mut [Box<dyn PlayerAgent>]) {
        let active = game.active_player();

        // Delegate phasing to the phase module.
        crate::phase::untap::do_phasing(game, active);

        // Untap permanents — uses agent interaction for "may choose not to untap".
        let cards: Vec<crate::ids::CardId> =
            game.cards_in_zone(ZoneType::Battlefield, active).to_vec();
        for cid in cards {
            if game.card(cid).exerted {
                game.card_mut(cid).clear_exerted();
            } else {
                let optional_keyword =
                    "You may choose not to untap CARDNAME during your untap step.";
                let should_untap = if game.card(cid).has_keyword(optional_keyword) {
                    let question = format!("Untap {}?", game.card(cid).card_name);
                    let source_name = game.card(cid).card_name.clone();
                    agents[active.index()].choose_binary(
                        active,
                        &question,
                        crate::agent::BinaryChoiceKind::UntapOrLeaveTapped,
                        Some(true),
                        Some(&source_name),
                        None,
                    )
                } else {
                    true
                };
                if should_untap {
                    game.untap(cid);
                }
            }
        }
        self.pool_mut(active).reset_pool();
    }

    pub fn step_draw(&mut self, game: &mut GameState) {
        let active = game.active_player();
        // Skip draw on turn 1
        if game.turn.turn_number > 1 {
            if let Some(card_id) = game.player_draw_one_for_turn(active) {
                let drawn_snapshot = game.player(active).drawn_this_turn;
                // Fire Drawn trigger for turn draw
                self.trigger_handler.run_trigger(
                    TriggerType::Drawn,
                    RunParams {
                        card: Some(card_id),
                        player: Some(active),
                        drawn_this_turn_snapshot: Some(drawn_snapshot),
                        ..Default::default()
                    },
                    false,
                );
                // Match Drawn triggers immediately so Number$ N checks see
                // the correct drawn count at fire time.
                if self.trigger_handler.has_number_drawn_triggers(game) {
                    self.trigger_handler.flush_waiting_triggers(game);
                }
            }
        }
    }
    pub fn step_with_priority(
        &mut self,
        game: &mut GameState,
        agents: &mut [Box<dyn PlayerAgent>],
        is_main_phase: bool,
    ) {
        self.game_log.log(
            GameLogEntryType::Info,
            2,
            format!(
                "Priority window opened ({}, stack depth: {})",
                if is_main_phase {
                    "main-phase speed"
                } else {
                    "instant speed only"
                },
                game.stack.len()
            ),
        );
        self.with_shared_state_mutation(game, agents, |_this, game, _agents| {
            game.turn.priority_player = game.active_player();
        });
        loop {
            if game.game_over {
                return;
            }

            // 1. Give players priority (process_triggers + SBA are handled
            //    inside priority_round at the top of each iteration, matching
            //    Java's checkStateBasedEffects() → addAllTriggeredAbilitiesToStack()
            //    before chooseSpellAbilityToPlay()).
            self.priority_round(game, agents, is_main_phase);

            if game.game_over {
                return;
            }

            // 3. If stack is empty after everyone passed, the phase ends
            if game.stack.is_empty() {
                break;
            }

            // 4. Resolve top of stack (resolve_stack resolves one and gives priority)
            self.with_shared_state_mutation(game, agents, |this, game, agents| {
                this.resolve_stack(game, agents);
            });
        }
    }
    pub fn step_main_phase(&mut self, game: &mut GameState, agents: &mut [Box<dyn PlayerAgent>]) {
        self.step_with_priority(game, agents, true);
    }

    pub fn step_cleanup(&mut self, game: &mut GameState, agents: &mut [Box<dyn PlayerAgent>]) {
        let active = game.active_player();

        // Discard down to max hand size — player chooses which cards to discard.
        // Mirrors Java's Player.discard() during cleanup step.
        let hand_size = game.zone(ZoneType::Hand, active).len() as i32;
        let max = game.player(active).max_hand_size;
        if hand_size > max {
            let to_discard = (hand_size - max) as usize;
            let hand: Vec<CardId> = game.cards_in_zone(ZoneType::Hand, active).to_vec();
            agents[active.index()].snapshot_state(game, &self.mana_pools);
            self.game_log.log(
                GameLogEntryType::PriorityWaiting,
                2,
                format!(
                    "Waiting for {} discard decision (choose {})",
                    game.player(active).name,
                    to_discard
                ),
            );
            let chosen = agents[active.index()].choose_discard(active, &hand, to_discard);
            self.game_log.log(
                GameLogEntryType::PriorityResponse,
                2,
                format!(
                    "{} selected {} card(s) to discard",
                    game.player(active).name,
                    chosen.len().min(to_discard)
                ),
            );
            for card_id in chosen.iter().take(to_discard) {
                if game.card(*card_id).zone == ZoneType::Hand {
                    effects::helpers::discard_with_madness_replacement(
                        game,
                        &mut self.trigger_handler,
                        *card_id,
                        active,
                    );
                }
            }
        }

        // Process any triggers from cleanup discard (e.g. Madness triggers that
        // need to resolve before end of turn). Mirrors Java's cleanup step which
        // processes triggers after discard-to-hand-size.
        self.process_triggers(game, agents);
        if !game.stack.is_empty() {
            self.resolve_stack(game, agents);
        }

        // Reset fog flag (issue #22: Fog effect lasts until end of turn).
        game.prevent_all_combat_damage = false;

        // Reset end-of-turn flags (issue #22).
        game.end_turn_requested = false;
        game.end_combat_requested = false;
        game.extra_combat_phases = 0;
        game.stack.reset_max_distinct_sources();

        // Empty mana pool at end of turn (cleanup step), per Magic rules.
        self.pool_mut(active).reset_pool();
        self.trigger_handler.clear_this_turn_delayed_trigger();

        // Remove temporary command-zone effect cards created by AB$ Effect
        // that expire at end of turn.
        // These helper effect cards should cease to exist when they expire;
        // keeping them in Exile causes parity drift versus Java snapshots.
        let temp_effect_ids: Vec<CardId> = game
            .cards
            .iter()
            .filter(|c| c.zone == ZoneType::Command && c.temp_effect_until_eot)
            .map(|c| c.id)
            .collect();
        for effect_id in temp_effect_ids {
            if game.card(effect_id).zone == ZoneType::Command {
                let controller = game.card(effect_id).controller;
                game.zone_mut(ZoneType::Command, controller)
                    .remove(effect_id);
                game.card_mut(effect_id).set_zone(ZoneType::None);
            }
        }

        // Return stolen creatures (LoseControl$ EOT) to their original controllers
        let stolen: Vec<(CardId, crate::ids::PlayerId)> = game
            .cards
            .iter()
            .filter(|c| c.zone == ZoneType::Battlefield && c.original_controller_eot.is_some())
            .map(|c| (c.id, c.original_controller_eot.unwrap()))
            .collect();
        for (card_id, original) in stolen {
            let current = game.card(card_id).controller;
            game.card_mut(card_id).clear_original_controller_eot();
            // Remove granted keywords (e.g. Haste from Act of Aggression)
            game.card_mut(card_id).clear_granted_keywords();
            if current != original {
                game.change_controller(card_id, original);
            }
        }

        // Player-owned cleanup state that expires at end of turn.
        let player_ids = game.player_order.clone();
        for player in player_ids {
            game.player_cleanup_turn_state(player);
        }

        // Remove damage and reset until-end-of-turn effects on all battlefield permanents
        for i in 0..game.cards.len() {
            if game.cards[i].zone == ZoneType::Battlefield {
                // Restore animate state before checking creature status (issue #52).
                // Must happen first: if the card was animated into a creature but its base
                // form is not a creature, we still need to reset its type/P/T.
                if let Some(state) = game.cards[i].animate_state.take() {
                    game.cards[i].restore_animate_snapshot(
                        state.original_type_line,
                        state.original_base_power,
                        state.original_base_toughness,
                        state.original_color,
                    );
                    // Clear damage accumulated while animated as a creature.
                    // Without this, damage leaks into the next turn if the
                    // card is re-animated (the is_creature() check below would
                    // miss it since the card is no longer a creature).
                    game.cards[i].clear_damage();
                }

                if game.cards[i].is_creature() {
                    let keep_damage =
                        crate::staticability::static_ability_no_cleanup_damage::damage_not_removed(
                            &game.cards,
                            &game.cards[i],
                        );
                    if !keep_damage {
                        game.cards[i].clear_damage();
                    }
                    game.cards[i].reset_turn_modifiers();
                    game.cards[i].clear_pump_keywords();
                    // Remove triggers added by Animate effects (Supernatural Stamina etc.)
                    game.cards[i].clear_pump_triggers();
                    game.cards[i].clear_deathtouch_damage();
                    // Reset regeneration shields at end of turn (issue #22).
                    game.cards[i].reset_regeneration_shields();
                    // Reset damage prevention shields at end of turn.
                    // Mirrors Java's DamagePreventEffect which exiles Effect cards at EOT.
                    game.cards[i].reset_shield_count();
                    // Reset per-turn damage history.
                    game.cards[i].damage_history.new_turn();
                }
            }
        }
    }
    pub(crate) fn emit_phase_trigger(
        &mut self,
        game: &mut GameState,
        agents: &mut [Box<dyn PlayerAgent>],
        phase: PhaseType,
    ) {
        let active = game.active_player();
        let phase_pending = self.trigger_handler.run_trigger_with_game(
            game,
            TriggerType::Phase,
            RunParams {
                phase: Some(phase),
                player: Some(active),
                ..Default::default()
            },
            false,
        );
        let _ = crate::trigger::trigger_runtime::process_pending_triggers(
            &mut self.trigger_handler,
            &self.mana_pools,
            game,
            agents,
            phase_pending,
        );
        // Fire Always trigger alongside every phase trigger.
        let always_pending = self.trigger_handler.run_trigger_with_game(
            game,
            TriggerType::Always,
            RunParams {
                phase: Some(phase),
                player: Some(active),
                ..Default::default()
            },
            false,
        );
        let _ = crate::trigger::trigger_runtime::process_pending_triggers(
            &mut self.trigger_handler,
            &self.mana_pools,
            game,
            agents,
            always_pending,
        );
    }

    /// Fire DamageDone and LifeGained triggers from combat damage events.
    /// DamageDone fires per source-target pair; DamageDoneOnce fires once per
    /// target with aggregated damage (mirrors Java CardDamageMap.triggerDamageOnce).
    pub(crate) fn fire_combat_damage_triggers(&mut self, events: &[combat::CombatDamageEvent]) {
        use std::collections::HashMap;
        use crate::ids::{CardId, PlayerId};

        // Per-event: fire DamageDone and LifeGained
        for event in events {
            self.trigger_handler.run_trigger(
                TriggerType::DamageDone,
                RunParams {
                    damage_source: Some(event.source),
                    damage_target_player: event.target_player,
                    damage_target_card: event.target_card,
                    damage_amount: Some(event.amount),
                    is_combat_damage: Some(event.is_combat),
                    ..Default::default()
                },
                false,
            );
            if let Some(player) = event.lifelink_player {
                if event.lifelink_amount > 0 {
                    self.trigger_handler.run_trigger(
                        TriggerType::LifeGained,
                        RunParams {
                            player: Some(player),
                            life_amount: Some(event.lifelink_amount),
                            source_card: Some(event.source),
                            ..Default::default()
                        },
                        false,
                    );
                }
            }
        }

        // Aggregate damage by target, then fire DamageDoneOnce once per target.
        // Mirrors Java's CardDamageMap.triggerDamageOnce() which batches damage
        // so Enrage (e.g. Raptor Hatchling) fires only once per damage step.
        #[derive(Hash, PartialEq, Eq, Clone, Copy)]
        enum Target {
            Card(CardId),
            Player(PlayerId),
        }
        let mut by_target: HashMap<Target, i32> = HashMap::new();
        for event in events {
            if event.amount <= 0 {
                continue;
            }
            let target = if let Some(cid) = event.target_card {
                Target::Card(cid)
            } else if let Some(pid) = event.target_player {
                Target::Player(pid)
            } else {
                continue;
            };
            *by_target.entry(target).or_insert(0) += event.amount;
        }
        for (target, total) in by_target {
            if total <= 0 {
                continue;
            }
            let params = match target {
                Target::Card(cid) => RunParams {
                    damage_target_card: Some(cid),
                    damage_amount: Some(total),
                    is_combat_damage: Some(true),
                    ..Default::default()
                },
                Target::Player(pid) => RunParams {
                    damage_target_player: Some(pid),
                    damage_amount: Some(total),
                    is_combat_damage: Some(true),
                    ..Default::default()
                },
            };
            self.trigger_handler
                .run_trigger(TriggerType::DamageDoneOnce, params, false);
        }
    }

    /// Suspend upkeep processing: for each suspended card in exile owned by the
    /// active player, remove a time counter. If the last counter was removed,
    /// cast the card for free (and grant haste if creature).
    /// Mirrors Java's GameAction.handleSuspendTriggers().
    pub(crate) fn process_suspend_upkeep(
        &mut self,
        game: &mut GameState,
        agents: &mut [Box<dyn PlayerAgent>],
    ) {
        let active = game.active_player();
        let exile: Vec<CardId> = game.cards_in_zone(ZoneType::Exile, active).to_vec();
        for card_id in exile {
            let card = game.card(card_id);
            // Check if the card has suspend keyword and time counters
            if card.get_suspend_cost().is_none() {
                continue;
            }
            let time_counters = *card
                .counters
                .get(&crate::card::CounterType::Time)
                .unwrap_or(&0);
            if time_counters <= 0 {
                continue;
            }
            // Remove one time counter
            game.card_mut(card_id)
                .remove_counter(&crate::card::CounterType::Time, 1);

            // Emit CounterRemoved trigger
            self.trigger_handler.run_trigger(
                TriggerType::CounterRemoved,
                RunParams {
                    card: Some(card_id),
                    player: Some(active),
                    ..Default::default()
                },
                false,
            );

            let remaining = *game
                .card(card_id)
                .counters
                .get(&crate::card::CounterType::Time)
                .unwrap_or(&0);
            if remaining <= 0 {
                // Last counter removed — cast for free
                let card_name = game.card(card_id).card_name.clone();
                let is_creature = game.card(card_id).is_creature();
                let is_permanent = game.card(card_id).is_permanent();
                // Move from exile to stack
                game.player_record_spell_cast(active, card_id);

                // Emit SpellCast trigger
                self.trigger_handler.run_trigger(
                    TriggerType::SpellCast,
                    RunParams {
                        spell_card: Some(card_id),
                        spell_controller: Some(active),
                        ..Default::default()
                    },
                    false,
                );

                // Build SpellAbility
                let mut sa =
                    crate::spellability::build_spell_ability_for_card_cast(game, card_id, active);
                sa.alt_cost = Some(crate::spellability::AlternativeCost::Suspend);
                sa.setup_targets(game, agents, &self.mana_pools);

                let entry = StackEntry {
                    id: 0,
                    spell_ability: sa,
                    is_creature_spell: is_creature,
                    is_permanent_spell: is_permanent,
                    cast_from_zone: Some(ZoneType::Exile),
                    optional_trigger_decider: None,
                    optional_trigger_description: None,
                    optional_trigger_source_name: None,
                };

                game.stack.push(entry);
                self.log_stack_push(&card_name, &game.player(active).name);
                self.move_card_with_runtime(game, card_id, ZoneType::Stack, active, agents);
                crate::agent::notify_all_agents(
                    agents,
                    crate::agent::GameLogEvent::stack(format!(
                        "Suspend: casting {} for free!",
                        card_name
                    ))
                    .with_player(active)
                    .with_card(card_id),
                );

                // Grant haste if creature (suspend creatures get haste)
                if is_creature {
                    if !game.card(card_id).has_haste() {
                        game.card_mut(card_id).granted_keywords.add("Haste");
                    }
                }
            }
        }
    }
}
