use super::*;

impl GameLoop {
    pub(crate) fn run_turn_state_machine(
        &mut self,
        game: &mut GameState,
        agents: &mut [Box<dyn PlayerAgent>],
    ) {
        // Fire TurnBegin trigger at the start of each turn.
        let active = game.active_player();
        self.trigger_handler.run_trigger(
            TriggerType::TurnBegin,
            RunParams {
                player: Some(active),
                ..Default::default()
            },
            false,
        );

        let mut state = TurnMachineState::Untap;
        while !game.game_over && state != TurnMachineState::Done {
            // EndTurn (issue #22): if end_turn_requested, skip directly to cleanup.
            if game.end_turn_requested
                && state != TurnMachineState::Cleanup
                && state != TurnMachineState::Done
            {
                game.end_turn_requested = false;
                self.combat.clear_with_cards(&mut game.cards);
                state = TurnMachineState::Cleanup;
                continue;
            }
            state = match state {
                TurnMachineState::Untap => {
                    // SkipPhase: skip untap if flag set
                    let active = game.active_player();
                    if game.player(active).skip_next_untap {
                        game.player_mut(active).skip_next_untap = false;
                        TurnMachineState::Upkeep
                    } else {
                        self.apply_turn_event(
                            game,
                            agents,
                            TurnEvent::EnterPhase {
                                phase: PhaseType::Untap,
                                emit_phase_trigger: false,
                            },
                        );
                        self.apply_turn_event(game, agents, TurnEvent::UntapStep);
                        TurnMachineState::Upkeep
                    }
                }
                TurnMachineState::Upkeep => {
                    self.apply_turn_event(
                        game,
                        agents,
                        TurnEvent::EnterPhase {
                            phase: PhaseType::Upkeep,
                            emit_phase_trigger: true,
                        },
                    );
                    self.apply_turn_event(
                        game,
                        agents,
                        TurnEvent::PriorityWindow {
                            is_main_phase: false,
                        },
                    );
                    // Cumulative upkeep is now handled as a Phase trigger
                    // (generated by generate_keyword_triggers from the keyword),
                    // so it fires alongside other upkeep triggers (e.g. Deep Spawn)
                    // and is ordered by the player. No separate procedural call needed.
                    TurnMachineState::Draw
                }
                TurnMachineState::Draw => {
                    // SkipPhase: skip draw if flag set
                    let active = game.active_player();
                    if game.player(active).skip_next_draw {
                        game.player_mut(active).skip_next_draw = false;
                        TurnMachineState::Main1
                    } else {
                        // Java parity: Java's isSkippingPhase(DRAW) returns true on turn 1
                        // in a 2-player game, skipping the entire Draw phase (no draw, no
                        // priority window). Rust skips the draw card itself but was still
                        // giving a priority window, consuming 2 extra RNG calls on Turn 1.
                        let skip_draw_phase = game.turn.turn_number == 1 && game.players.len() == 2;
                        if skip_draw_phase {
                            TurnMachineState::Main1
                        } else {
                            self.apply_turn_event(
                                game,
                                agents,
                                TurnEvent::EnterPhase {
                                    phase: PhaseType::Draw,
                                    emit_phase_trigger: true,
                                },
                            );
                            self.apply_turn_event(game, agents, TurnEvent::DrawStep);
                            self.apply_turn_event(
                                game,
                                agents,
                                TurnEvent::PriorityWindow {
                                    is_main_phase: false,
                                },
                            );
                            TurnMachineState::Main1
                        }
                    }
                }
                TurnMachineState::Main1 => {
                    self.apply_turn_event(
                        game,
                        agents,
                        TurnEvent::EnterPhase {
                            phase: PhaseType::Main1,
                            emit_phase_trigger: true,
                        },
                    );
                    self.apply_turn_event(
                        game,
                        agents,
                        TurnEvent::PriorityWindow {
                            is_main_phase: true,
                        },
                    );
                    TurnMachineState::Combat
                }
                TurnMachineState::Combat => {
                    // SkipPhase: skip combat if flag set
                    let active = game.active_player();
                    if game.player(active).skip_next_combat {
                        game.player_mut(active).skip_next_combat = false;
                        TurnMachineState::Main2
                    } else {
                        self.apply_turn_event(game, agents, TurnEvent::CombatStep);
                        // Extra combat phases (issue #22, AddPhase effect)
                        if game.extra_combat_phases > 0 {
                            game.extra_combat_phases -= 1;
                            TurnMachineState::Combat // loop back for another combat
                        } else {
                            TurnMachineState::Main2
                        }
                    }
                }
                TurnMachineState::Main2 => {
                    self.apply_turn_event(
                        game,
                        agents,
                        TurnEvent::EnterPhase {
                            phase: PhaseType::Main2,
                            emit_phase_trigger: true,
                        },
                    );
                    self.apply_turn_event(
                        game,
                        agents,
                        TurnEvent::PriorityWindow {
                            is_main_phase: true,
                        },
                    );
                    TurnMachineState::EndOfTurn
                }
                TurnMachineState::EndOfTurn => {
                    self.apply_turn_event(
                        game,
                        agents,
                        TurnEvent::EnterPhase {
                            phase: PhaseType::EndOfTurn,
                            emit_phase_trigger: true,
                        },
                    );
                    self.apply_turn_event(
                        game,
                        agents,
                        TurnEvent::PriorityWindow {
                            is_main_phase: false,
                        },
                    );
                    TurnMachineState::Cleanup
                }
                TurnMachineState::Cleanup => {
                    self.apply_turn_event(
                        game,
                        agents,
                        TurnEvent::EnterPhase {
                            phase: PhaseType::Cleanup,
                            emit_phase_trigger: false,
                        },
                    );
                    self.apply_turn_event(game, agents, TurnEvent::CleanupStep);
                    self.apply_turn_event(game, agents, TurnEvent::AdvanceTurn);
                    TurnMachineState::Done
                }
                TurnMachineState::Done => TurnMachineState::Done,
            };
        }
    }

    fn apply_turn_event(
        &mut self,
        game: &mut GameState,
        agents: &mut [Box<dyn PlayerAgent>],
        event: TurnEvent,
    ) {
        if game.game_over {
            return;
        }
        match event {
            TurnEvent::EnterPhase {
                phase,
                emit_phase_trigger,
            } => {
                // LKI: Snapshot battlefield state before phase transition.
                // Mirrors Java PhaseHandler line 1103: game.copyLastState().
                game.copy_last_state();
                self.set_phase(game, agents, phase);
                if emit_phase_trigger {
                    self.emit_phase_trigger(game, phase);
                }
                // Suspend: at the beginning of each upkeep, remove a time counter
                // from each suspended card in exile. If last counter removed, cast for free.
                if phase == PhaseType::Upkeep {
                    self.process_suspend_upkeep(game, agents);
                }
            }
            TurnEvent::PriorityWindow { is_main_phase } => {
                self.step_with_priority(game, agents, is_main_phase);
            }
            TurnEvent::UntapStep => {
                self.with_shared_state_mutation(game, agents, |this, game, agents| {
                    this.step_untap(game, agents);
                });
            }
            TurnEvent::DrawStep => {
                self.with_shared_state_mutation(game, agents, |this, game, _agents| {
                    this.step_draw(game);
                });
            }
            TurnEvent::CombatStep => {
                self.step_combat(game, agents);
            }
            TurnEvent::CleanupStep => {
                self.with_shared_state_mutation(game, agents, |this, game, agents| {
                    this.step_cleanup(game, agents);
                });
            }
            TurnEvent::AdvanceTurn => {
                self.with_shared_state_mutation(game, agents, |_this, game, _agents| {
                    // Extra turns (issue #22): if the queue is non-empty, the
                    // front player gets the next turn instead of the normal
                    // rotation.  Mirrors Java's PhaseHandler.handleNextTurn().
                    if let Some(extra_turn) = game.extra_turns.pop_front() {
                        game.turn.active_player = extra_turn.player;
                        game.turn.priority_player = extra_turn.player;
                        game.turn.turn_number += 1;
                        game.turn.combat_attackers_declared = false;
                        game.turn.combat_blockers_declared = false;
                        game.turn.drawn_for_turn = false;
                        // SkipUntap on extra turn (issue #22, AddTurn parity fix)
                        if extra_turn.skip_untap {
                            game.player_mut(extra_turn.player).skip_next_untap = true;
                        }
                    } else {
                        game.turn.next_player_turn(&game.player_order.clone());
                    }
                });
            }
        }
    }

    pub fn step_untap(&mut self, game: &mut GameState, agents: &mut [Box<dyn PlayerAgent>]) {
        let active = game.active_player();

        // Phase-in (issue #22): phase in all phased-out permanents controlled by active player.
        for i in 0..game.cards.len() {
            if game.cards[i].phased_out
                && game.cards[i].controller == active
                && game.cards[i].zone == ZoneType::Battlefield
            {
                game.cards[i].phased_out = false;
            }
        }

        // Untap permanents, skipping exerted ones and resetting their flag.
        let cards: Vec<crate::ids::CardId> =
            game.cards_in_zone(ZoneType::Battlefield, active).to_vec();
        for cid in cards {
            if game.card(cid).exerted {
                // Exerted creatures don't untap this turn; reset flag so they untap next turn.
                game.card_mut(cid).exerted = false;
            } else {
                let optional_keyword =
                    "You may choose not to untap CARDNAME during your untap step.";
                let should_untap = if game.card(cid).has_keyword(optional_keyword) {
                    let question = format!("Untap {}?", game.card(cid).card_name);
                    let source_name = game.card(cid).card_name.clone();
                    agents[active.index()].choose_binary(
                        active,
                        &question,
                        crate::agent::BinaryChoiceKind::UntapOrLeaveTapped,
                        Some(true),
                        Some(&source_name),
                        None,
                    )
                } else {
                    true
                };
                if should_untap {
                    game.untap(cid);
                }
            }
        }
        self.pool_mut(active).empty();
    }

    pub fn step_draw(&mut self, game: &mut GameState) {
        let active = game.active_player();
        // Skip draw on turn 1
        if game.turn.turn_number > 1 {
            if let Some(card_id) = game.draw_card(active) {
                // Fire Drawn trigger for turn draw
                self.trigger_handler.run_trigger(
                    TriggerType::Drawn,
                    RunParams {
                        card: Some(card_id),
                        player: Some(active),
                        ..Default::default()
                    },
                    false,
                );
            }
        }
    }
    pub fn step_with_priority(
        &mut self,
        game: &mut GameState,
        agents: &mut [Box<dyn PlayerAgent>],
        is_main_phase: bool,
    ) {
        self.game_log.log(
            GameLogEntryType::Info,
            2,
            format!(
                "Priority window opened ({}, stack depth: {})",
                if is_main_phase {
                    "main-phase speed"
                } else {
                    "instant speed only"
                },
                game.stack.len()
            ),
        );
        self.with_shared_state_mutation(game, agents, |_this, game, _agents| {
            game.turn.priority_player = game.active_player();
        });
        loop {
            if game.game_over {
                return;
            }

            // 1. Process any pending triggers and put them on the stack
            self.with_shared_state_mutation(game, agents, |this, game, agents| {
                this.process_triggers(game, agents);
            });

            // 2. Give players priority
            self.priority_round(game, agents, is_main_phase);

            if game.game_over {
                return;
            }

            // 3. If stack is empty after everyone passed, the phase ends
            if game.stack.is_empty() {
                break;
            }

            // 4. Resolve top of stack (resolve_stack resolves one and gives priority)
            self.with_shared_state_mutation(game, agents, |this, game, agents| {
                this.resolve_stack(game, agents);
            });
        }
    }
    pub fn step_main_phase(&mut self, game: &mut GameState, agents: &mut [Box<dyn PlayerAgent>]) {
        self.step_with_priority(game, agents, true);
    }

    pub fn step_cleanup(&mut self, game: &mut GameState, agents: &mut [Box<dyn PlayerAgent>]) {
        let active = game.active_player();

        // Discard down to max hand size — player chooses which cards to discard.
        // Mirrors Java's Player.discard() during cleanup step.
        let hand_size = game.zone(ZoneType::Hand, active).len() as i32;
        let max = game.player(active).max_hand_size;
        if hand_size > max {
            let to_discard = (hand_size - max) as usize;
            let hand: Vec<CardId> = game.cards_in_zone(ZoneType::Hand, active).to_vec();
            agents[active.index()].snapshot_state(game, &self.mana_pools);
            self.game_log.log(
                GameLogEntryType::PriorityWaiting,
                2,
                format!(
                    "Waiting for {} discard decision (choose {})",
                    game.player(active).name,
                    to_discard
                ),
            );
            let chosen = agents[active.index()].choose_discard(active, &hand, to_discard);
            self.game_log.log(
                GameLogEntryType::PriorityResponse,
                2,
                format!(
                    "{} selected {} card(s) to discard",
                    game.player(active).name,
                    chosen.len().min(to_discard)
                ),
            );
            for card_id in chosen.iter().take(to_discard) {
                if game.card(*card_id).zone == ZoneType::Hand {
                    let has_madness = game.card(*card_id).get_madness_cost().is_some();
                    if has_madness {
                        // Madness: exile instead of graveyard (can cast for madness cost)
                        game.move_card(*card_id, ZoneType::Exile, active);
                        effects::emit_zone_trigger(
                            &mut self.trigger_handler,
                            *card_id,
                            ZoneType::Hand,
                            ZoneType::Exile,
                        );
                    } else {
                        game.move_card(*card_id, ZoneType::Graveyard, active);
                        effects::emit_zone_trigger(
                            &mut self.trigger_handler,
                            *card_id,
                            ZoneType::Hand,
                            ZoneType::Graveyard,
                        );
                    }
                    // Fire Discarded trigger regardless of destination
                    self.trigger_handler.run_trigger(
                        TriggerType::Discarded,
                        RunParams {
                            card: Some(*card_id),
                            player: Some(active),
                            ..Default::default()
                        },
                        false,
                    );
                }
            }
        }

        // Reset fog flag (issue #22: Fog effect lasts until end of turn).
        game.prevent_all_combat_damage = false;

        // Reset end-of-turn flags (issue #22).
        game.end_turn_requested = false;
        game.end_combat_requested = false;
        game.extra_combat_phases = 0;

        // Monarch draw (issue #22): at end of turn, the monarch draws a card.
        if let Some(monarch_id) = game.monarch {
            if game.player(monarch_id).is_alive() && monarch_id == active {
                game.draw_card(monarch_id);
            }
        }

        // Empty mana pool at end of turn (cleanup step), per Magic rules.
        self.pool_mut(active).empty();

        // Remove temporary command-zone effect cards created by AB$ Effect
        // that expire at end of turn.
        // These helper effect cards should cease to exist when they expire;
        // keeping them in Exile causes parity drift versus Java snapshots.
        let temp_effect_ids: Vec<CardId> = game
            .cards
            .iter()
            .filter(|c| c.zone == ZoneType::Command && c.temp_effect_until_eot)
            .map(|c| c.id)
            .collect();
        for effect_id in temp_effect_ids {
            if game.card(effect_id).zone == ZoneType::Command {
                let controller = game.card(effect_id).controller;
                game.zone_mut(ZoneType::Command, controller)
                    .remove(effect_id);
                game.cards[effect_id.index()].zone = ZoneType::None;
            }
        }

        // Return stolen creatures (LoseControl$ EOT) to their original controllers
        let stolen: Vec<(CardId, crate::ids::PlayerId)> = game
            .cards
            .iter()
            .filter(|c| c.zone == ZoneType::Battlefield && c.original_controller_eot.is_some())
            .map(|c| (c.id, c.original_controller_eot.unwrap()))
            .collect();
        for (card_id, original) in stolen {
            let current = game.card(card_id).controller;
            game.cards[card_id.index()].original_controller_eot = None;
            // Remove granted keywords (e.g. Haste from Act of Aggression)
            game.cards[card_id.index()].granted_keywords.clear();
            if current != original {
                game.change_controller(card_id, original);
            }
        }

        // Remove damage and reset until-end-of-turn effects on all battlefield permanents
        for i in 0..game.cards.len() {
            if game.cards[i].zone == ZoneType::Battlefield {
                // Restore animate state before checking creature status (issue #52).
                // Must happen first: if the card was animated into a creature but its base
                // form is not a creature, we still need to reset its type/P/T.
                if let Some(state) = game.cards[i].animate_state.take() {
                    game.cards[i].type_line = state.original_type_line;
                    game.cards[i].base_power = state.original_base_power;
                    game.cards[i].base_toughness = state.original_base_toughness;
                    game.cards[i].color = state.original_color;
                    // Clear damage accumulated while animated as a creature.
                    // Without this, damage leaks into the next turn if the
                    // card is re-animated (the is_creature() check below would
                    // miss it since the card is no longer a creature).
                    game.cards[i].damage = 0;
                }

                if game.cards[i].is_creature() {
                    let keep_damage =
                        crate::staticability::static_ability_no_cleanup_damage::damage_not_removed(
                            &game.cards,
                            &game.cards[i],
                        );
                    if !keep_damage {
                        game.cards[i].damage = 0;
                    }
                    game.cards[i].power_modifier = 0;
                    game.cards[i].toughness_modifier = 0;
                    game.cards[i].pump_keywords.clear();
                    game.cards[i].has_deathtouch_damage = false;
                    // Reset regeneration shields at end of turn (issue #22).
                    game.cards[i].regeneration_shields = 0;
                    // Reset per-turn damage history.
                    game.cards[i].damage_history.new_turn();
                }
            }
        }
    }
    pub(crate) fn emit_phase_trigger(&mut self, game: &GameState, phase: PhaseType) {
        let active = game.active_player();
        self.trigger_handler.run_trigger(
            TriggerType::Phase,
            RunParams {
                phase: Some(phase),
                player: Some(active),
                ..Default::default()
            },
            false,
        );
        // Fire Always trigger alongside every phase trigger.
        self.trigger_handler.run_trigger(
            TriggerType::Always,
            RunParams {
                phase: Some(phase),
                player: Some(active),
                ..Default::default()
            },
            false,
        );
    }

    /// Fire DamageDone and LifeGained triggers from combat damage events.
    pub(crate) fn fire_combat_damage_triggers(&mut self, events: &[combat::CombatDamageEvent]) {
        for event in events {
            self.trigger_handler.run_trigger(
                TriggerType::DamageDone,
                RunParams {
                    damage_source: Some(event.source),
                    damage_target_player: event.target_player,
                    damage_target_card: event.target_card,
                    damage_amount: Some(event.amount),
                    is_combat_damage: Some(event.is_combat),
                    ..Default::default()
                },
                false,
            );
            if let Some(player) = event.lifelink_player {
                if event.lifelink_amount > 0 {
                    self.trigger_handler.run_trigger(
                        TriggerType::LifeGained,
                        RunParams {
                            player: Some(player),
                            life_amount: Some(event.lifelink_amount),
                            ..Default::default()
                        },
                        false,
                    );
                }
            }
        }
    }

    /// Suspend upkeep processing: for each suspended card in exile owned by the
    /// active player, remove a time counter. If the last counter was removed,
    /// cast the card for free (and grant haste if creature).
    /// Mirrors Java's GameAction.handleSuspendTriggers().
    pub(crate) fn process_suspend_upkeep(
        &mut self,
        game: &mut GameState,
        agents: &mut [Box<dyn PlayerAgent>],
    ) {
        let active = game.active_player();
        let exile: Vec<CardId> = game.cards_in_zone(ZoneType::Exile, active).to_vec();
        for card_id in exile {
            let card = game.card(card_id);
            // Check if the card has suspend keyword and time counters
            if card.get_suspend_cost().is_none() {
                continue;
            }
            let time_counters = *card
                .counters
                .get(&crate::card::CounterType::Time)
                .unwrap_or(&0);
            if time_counters <= 0 {
                continue;
            }
            // Remove one time counter
            game.card_mut(card_id)
                .remove_counter(&crate::card::CounterType::Time, 1);

            // Emit CounterRemoved trigger
            self.trigger_handler.run_trigger(
                TriggerType::CounterRemoved,
                RunParams {
                    card: Some(card_id),
                    player: Some(active),
                    ..Default::default()
                },
                false,
            );

            let remaining = *game
                .card(card_id)
                .counters
                .get(&crate::card::CounterType::Time)
                .unwrap_or(&0);
            if remaining <= 0 {
                // Last counter removed — cast for free
                let card_name = game.card(card_id).card_name.clone();
                let is_creature = game.card(card_id).is_creature();
                let is_permanent = game.card(card_id).is_permanent();
                let abilities = game.card(card_id).abilities.clone();

                // Move from exile to stack
                game.player_mut(active).spells_cast_this_turn += 1;

                // Emit SpellCast trigger
                self.trigger_handler.run_trigger(
                    TriggerType::SpellCast,
                    RunParams {
                        spell_card: Some(card_id),
                        spell_controller: Some(active),
                        ..Default::default()
                    },
                    false,
                );

                // Build SpellAbility
                let ability_text = abilities.first().cloned().unwrap_or_default();
                let mut sa = build_spell_ability(game, card_id, &ability_text, active);
                sa.is_spell = true;
                sa.alt_cost = Some(crate::spellability::AlternativeCost::Suspend);
                sa.setup_targets(game, agents, &self.mana_pools);

                let entry = StackEntry {
                    id: 0,
                    spell_ability: sa,
                    is_creature_spell: is_creature,
                    is_permanent_spell: is_permanent,
                    cast_from_zone: Some(ZoneType::Exile),
                    optional_trigger_decider: None,
                    optional_trigger_description: None,
                    optional_trigger_source_name: None,
                };

                game.stack.push(entry);
                self.log_stack_push(&card_name, &game.player(active).name);
                game.move_card(card_id, ZoneType::Stack, active);
                crate::agent::notify_all_agents(
                    agents,
                    crate::agent::GameLogEvent::stack(format!(
                        "Suspend: casting {} for free!",
                        card_name
                    ))
                    .with_player(active)
                    .with_card(card_id),
                );

                // Grant haste if creature (suspend creatures get haste)
                if is_creature {
                    if !game.card(card_id).has_haste() {
                        game.card_mut(card_id)
                            .granted_keywords
                            .push("Haste".to_string());
                    }
                }
            }
        }
    }
}
