//! GitHub issue creation and dedup via the `gh` CLI.
//!
//! Creates issues for significant parity failure clusters, and adds comments
//! to existing issues rather than creating duplicates.

use std::process::Command;

use crate::llm::LlmAnalysis;

/// Data for a parity failure issue.
pub struct IssueData {
    pub divergence_field: String,
    pub rust_value: String,
    pub java_value: String,
    pub total_failures: i64,
    pub first_seen: String,
    pub last_seen: String,
    pub deck_pair_table: Vec<DeckPairRow>,
    pub covered_cards: String,
    pub analysis: Option<LlmAnalysis>,
    pub repro_command: String,
}

/// A row in the deck pair table for the issue body.
pub struct DeckPairRow {
    pub deck1: String,
    pub deck2: String,
    pub failures: usize,
    pub sample_seed: u64,
}

/// GitHub issue manager.
pub struct GitHubIssues {
    repo: String,
}

impl GitHubIssues {
    /// Create a new issue manager.
    /// If `repo` is `None`, `gh` will auto-detect from the git remote.
    pub fn new(repo: Option<String>) -> Self {
        Self {
            repo: repo.unwrap_or_default(),
        }
    }

    /// Check if `gh` CLI is authenticated. Returns false if not available.
    pub fn is_available(&self) -> bool {
        Command::new("gh")
            .args(["auth", "status"])
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    }

    /// Search for an existing open issue matching this cluster.
    /// Returns the issue number if found.
    pub fn find_existing_issue(&self, divergence_field: &str) -> Option<i64> {
        let mut cmd = Command::new("gh");
        cmd.args(["issue", "list", "--label", "parity-failure"]);
        cmd.args(["--search", divergence_field]);
        cmd.args(["--state", "open", "--json", "number", "--limit", "1"]);

        if !self.repo.is_empty() {
            cmd.args(["--repo", &self.repo]);
        }

        let output = cmd.output().ok()?;
        if !output.status.success() {
            return None;
        }

        let text = String::from_utf8_lossy(&output.stdout);
        let parsed: serde_json::Value = serde_json::from_str(text.trim()).ok()?;
        parsed
            .as_array()?
            .first()?
            .get("number")?
            .as_i64()
    }

    /// Create a new GitHub issue. Returns the issue number.
    pub fn create_issue(&self, data: &IssueData) -> Result<i64, String> {
        let title = format!(
            "Parity divergence: {} ({} failures)",
            data.divergence_field, data.total_failures
        );

        let body = build_issue_body(data);

        let mut cmd = Command::new("gh");
        cmd.args(["issue", "create"]);
        cmd.args(["--title", &title]);
        cmd.args(["--label", "parity-failure,automated"]);
        cmd.args(["--body", &body]);

        if !self.repo.is_empty() {
            cmd.args(["--repo", &self.repo]);
        }

        let output = cmd.output().map_err(|e| format!("Failed to run gh: {e}"))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(format!("gh issue create failed: {stderr}"));
        }

        // gh outputs the issue URL, extract the number from it
        let stdout = String::from_utf8_lossy(&output.stdout);
        extract_issue_number(&stdout)
            .ok_or_else(|| format!("Could not parse issue number from: {stdout}"))
    }

    /// Add a comment to an existing issue with updated stats.
    pub fn add_comment(&self, issue_number: i64, data: &IssueData) -> Result<(), String> {
        let body = format!(
            "## Updated Parity Stats\n\n\
             **Total failures:** {}\n\
             **Last seen:** {}\n\n\
             ---\nGenerated by Parity Analysis Agent",
            data.total_failures, data.last_seen
        );

        let mut cmd = Command::new("gh");
        cmd.args([
            "issue",
            "comment",
            &issue_number.to_string(),
            "--body",
            &body,
        ]);

        if !self.repo.is_empty() {
            cmd.args(["--repo", &self.repo]);
        }

        let output = cmd.output().map_err(|e| format!("Failed to run gh: {e}"))?;
        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(format!("gh issue comment failed: {stderr}"));
        }
        Ok(())
    }
}

fn build_issue_body(data: &IssueData) -> String {
    let mut body = format!(
        "## Parity Failure Report\n\n\
         **Divergence:** `{}` -- Rust: `{}`, Java: `{}`\n\
         **Occurrences:** {}\n\
         **First seen:** {}\n\
         **Last seen:** {}\n",
        data.divergence_field,
        data.rust_value,
        data.java_value,
        data.total_failures,
        data.first_seen,
        data.last_seen,
    );

    if !data.deck_pair_table.is_empty() {
        body.push_str("\n### Affected Deck Pairs\n");
        body.push_str("| Deck 1 | Deck 2 | Failures | Sample Seed |\n");
        body.push_str("|--------|--------|----------|-------------|\n");
        for row in &data.deck_pair_table {
            body.push_str(&format!(
                "| {} | {} | {} | {} |\n",
                row.deck1, row.deck2, row.failures, row.sample_seed
            ));
        }
    }

    if !data.covered_cards.is_empty() {
        body.push_str(&format!("\n### Cards Involved\n{}\n", data.covered_cards));
    }

    if let Some(ref analysis) = data.analysis {
        body.push_str(&format!(
            "\n### AI Analysis\n{}\n\n**Suggested files:** {}\n",
            analysis.root_cause,
            analysis.files_to_check.join(", "),
        ));
    }

    body.push_str(&format!(
        "\n### Reproduction\n```\n{}\n```\n\n---\nGenerated by Parity Analysis Agent\n",
        data.repro_command,
    ));

    body
}

fn extract_issue_number(url: &str) -> Option<i64> {
    // gh outputs URLs like "https://github.com/owner/repo/issues/123"
    url.trim()
        .rsplit('/')
        .next()?
        .parse::<i64>()
        .ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extract_number_from_url() {
        assert_eq!(
            extract_issue_number("https://github.com/foo/bar/issues/42\n"),
            Some(42)
        );
    }

    #[test]
    fn extract_number_missing() {
        assert_eq!(extract_issue_number("no url here"), None);
    }
}
